app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app/config/routing_dev.yml

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error